# TODO: /!\ THIS DOCKERFILE IS JUST FOR TESTING PURPOSE, NOT OPTIMIZED

# Use a lightweight Node.js base image
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port your service uses (adjust as needed)
EXPOSE 3000

# Command to run the service
CMD ["npm", "run", "start:dev", "auth-service"]
